export const publicKeyPEM = `-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCnbVvRBSOxkzx6Re5GubrKzdwyInjW1S3IqaeFq5vCuLmhYSGvpvx28TQ4XVLJduro17SDXLRgLfvRP12wwImjCe05OTZfBAmsX4zj8U4uAJ8AzaDrCrRqb+/q6Ppu7aO7Alw95RvA/xXXBjXuTlYgfq1aM75ILWPTn6DHOkTToQIDAQAB
-----END PUBLIC KEY-----`;
